package com.example.a30days.model

import androidx.annotation.BoolRes
import androidx.annotation.DrawableRes
import androidx.annotation.IntegerRes
import androidx.annotation.StringRes
import com.example.a30days.R

data class Plant(
    @StringRes val name: Int,
    @StringRes val desc: Int,
    @DrawableRes val img: Int,
    @IntegerRes val price: Int,
    val type: PlantType,
    val recharge: RechargeSpeed,
)

enum class PlantType {
    Day, Night, Aquatic, NightAquatic, Roof
}

enum class RechargeSpeed {
    Fast, Slow, VerySlow
}

val plants = listOf(
    Plant(
        R.string.peashooter,
        R.string.peashooter_desc,
        R.drawable.peashooter,
        R.integer.peashooter,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.sunflower,
        R.string.sunflower_desc,
        R.drawable.sunflower,
        R.integer.sunflower,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.cherry_bomb,
        R.string.cherry_bomb_desc,
        R.drawable.cherry_bomb,
        R.integer.cherry_bomb,
        PlantType.Day,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.wall_nut,
        R.string.wall_nut_desc,
        R.drawable.wall_nut,
        R.integer.wall_nut,
        PlantType.Day,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.potato_mine,
        R.string.potato_mine_desc,
        R.drawable.potato_mine,
        R.integer.potato_mine,
        PlantType.Day,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.snow_pea,
        R.string.snow_pea_desc,
        R.drawable.snow_pea,
        R.integer.snow_pea,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.chomper,
        R.string.chomper_desc,
        R.drawable.chomper,
        R.integer.chomper,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.repeater,
        R.string.repeater_desc,
        R.drawable.repeater,
        R.integer.repeater,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.puff_shroom,
        R.string.puff_shroom_desc,
        R.drawable.puff_shroom,
        R.integer.puff_shroom,
        PlantType.Night,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.sun_shroom,
        R.string.sun_shroom_desc,
        R.drawable.sun_shroom,
        R.integer.sun_shroom,
        PlantType.Night,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.fume_shroom,
        R.string.fume_shroom_desc,
        R.drawable.fume_shroom,
        R.integer.fume_shroom,
        PlantType.Night,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.grave_buster,
        R.string.grave_buster_desc,
        R.drawable.grave_buster,
        R.integer.grave_buster,
        PlantType.Night,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.hypno_shroom,
        R.string.hypno_shroom_desc,
        R.drawable.hypno_shroom,
        R.integer.hypno_shroom,
        PlantType.Night,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.scaredy_shroom,
        R.string.scaredy_shroom_desc,
        R.drawable.scaredy_shroom,
        R.integer.scaredy_shroom,
        PlantType.Night,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.ice_shroom,
        R.string.ice_shroom_desc,
        R.drawable.ice_shroom,
        R.integer.ice_shroom,
        PlantType.Night,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.doom_shroom,
        R.string.doom_shroom_desc,
        R.drawable.doom_shroom,
        R.integer.doom_shroom,
        PlantType.Night,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.lily_pad,
        R.string.lily_pad_desc,
        R.drawable.lily_pad,
        R.integer.lily_pad,
        PlantType.Aquatic,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.squash,
        R.string.squash_desc,
        R.drawable.squash,
        R.integer.squash,
        PlantType.Day,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.threepeater,
        R.string.threepeater_desc,
        R.drawable.threepeater,
        R.integer.threepeater,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.tangle_kelp,
        R.string.tangle_kelp_desc,
        R.drawable.tangle_kelp,
        R.integer.tangle_kelp,
        PlantType.Aquatic,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.jalapeno,
        R.string.jalapeno_desc,
        R.drawable.jalapeno,
        R.integer.jalapeno,
        PlantType.Day,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.spikeweed,
        R.string.spikeweed_desc,
        R.drawable.spikeweed,
        R.integer.spikeweed,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.torchwood,
        R.string.torchwood_desc,
        R.drawable.torchwood,
        R.integer.torchwood,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.tall_nut,
        R.string.tall_nut_desc,
        R.drawable.tall_nut,
        R.integer.tall_nut,
        PlantType.Day,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.sea_shroom,
        R.string.sea_shroom_desc,
        R.drawable.sea_shroom,
        R.integer.sea_shroom,
        PlantType.NightAquatic,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.plantern,
        R.string.plantern_desc,
        R.drawable.plantern,
        R.integer.plantern,
        PlantType.Night,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.cactus,
        R.string.cactus_desc,
        R.drawable.cactus,
        R.integer.cactus,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.blover,
        R.string.blover_desc,
        R.drawable.blover,
        R.integer.blover,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.split_pea,
        R.string.split_pea_desc,
        R.drawable.split_pea,
        R.integer.split_pea,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.starfruit,
        R.string.starfruit_desc,
        R.drawable.starfruit,
        R.integer.starfruit,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.pumpkin,
        R.string.pumpkin_desc,
        R.drawable.pumpkin,
        R.integer.pumpkin,
        PlantType.Day,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.magnet_shroom,
        R.string.magnet_shroom_desc,
        R.drawable.magnet_shroom,
        R.integer.magnet_shroom,
        PlantType.Night,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.cabbage_pult,
        R.string.cabbage_pult_desc,
        R.drawable.cabbage_pult,
        R.integer.cabbage_pult,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.flower_pot,
        R.string.flower_pot_desc,
        R.drawable.flower_pot,
        R.integer.flower_pot,
        PlantType.Roof,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.kernel_pult,
        R.string.kernel_pult_desc,
        R.drawable.kernel_pult,
        R.integer.kernel_pult,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.coffee_bean,
        R.string.coffee_bean_desc,
        R.drawable.coffee_bean,
        R.integer.coffee_bean,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.garlic,
        R.string.garlic_desc,
        R.drawable.garlic,
        R.integer.garlic,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.umbrella_leaf,
        R.string.umbrella_leaf_desc,
        R.drawable.umbrella_leaf,
        R.integer.umbrella_leaf,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.marigold,
        R.string.marigold_desc,
        R.drawable.marigold,
        R.integer.marigold,
        PlantType.Day,
        RechargeSpeed.Slow
    ),
    Plant(
        R.string.melon_pult,
        R.string.melon_pult_desc,
        R.drawable.melon_pult,
        R.integer.melon_pult,
        PlantType.Day,
        RechargeSpeed.Fast
    ),
    Plant(
        R.string.gatling_pea,
        R.string.gatling_pea_desc,
        R.drawable.gatling_pea,
        R.integer.gatling_pea,
        PlantType.Day,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.twin_sunflower,
        R.string.twin_sunflower_desc,
        R.drawable.twin_sunflower,
        R.integer.twin_sunflower,
        PlantType.Day,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.gloom_shroom,
        R.string.gloom_shroom_desc,
        R.drawable.gloom_shroom,
        R.integer.gloom_shroom,
        PlantType.Night,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.cattail,
        R.string.cattail_desc,
        R.drawable.cattail,
        R.integer.cattail,
        PlantType.Aquatic,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.winter_melon,
        R.string.winter_melon_desc,
        R.drawable.winter_melon,
        R.integer.winter_melon,
        PlantType.Day,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.gold_magnet,
        R.string.gold_magnet_desc,
        R.drawable.gold_magnet,
        R.integer.gold_magnet,
        PlantType.Day,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.spikerock,
        R.string.spikerock_desc,
        R.drawable.spikerock,
        R.integer.spikerock,
        PlantType.Day,
        RechargeSpeed.VerySlow
    ),
    Plant(
        R.string.cob_cannon,
        R.string.cob_cannon_desc,
        R.drawable.cob_cannon,
        R.integer.cob_cannon,
        PlantType.Day,
        RechargeSpeed.VerySlow
    ),
)